Update patch set 1
Patch Set 1:

This is needed to pass android.security.cts.SELinuxDomainTest#testInitDomain

junit.framework.AssertionFailedError: Expected 1 process in SELinux domain "u:r:init:s0" Found "[pid: "1"    proctitle: "/init"    label: "u:r:init:s0"    vsize: 9400320, pid: "6297"    proctitle: "/system/bin/wcnss_filter"    label: "u:r:init:s0"    vsize: 22814720]" expected:<1> but was:<2>

Patch-set: 1