Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review+1
> 
> Seems good, but ideally they would have the same name
> Can you introduce a Soong namespace?

out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/oneplus/oneplus3/Android.bp:204:1: "TimeService" depends on undefined module "timeservice_app_cert"
Module "TimeService" is defined in namespace "vendor/oneplus/oneplus3" which can read these 2 namespaces: ["vendor/oneplus/oneplus3" "."]
Module "timeservice_app_cert" can be found in these namespaces: ["device/qcom/sepolicy-legacy-um/timeservice" "device/qcom/sepolicy/timeservice"]

adding to PRODUCT_SOONG_NAMESPACES isn't enough because vendor and sepolicy are under different namespaces, thus the sepolicy namespace must be explictly imported from vendor blueprint, it makes things worse and harder to implement the script.

Patch-set: 1
Reviewer: Gerrit User 10258 <10258@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>